# answer
# https://kodekloud.com/community/t/gihub-actions-course-lab-2-problem/468775/3
name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-14, windows-latest]
          py-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}

# name: Installing Python

# on: [push]

# jobs:
#   build:

#     runs-on: ${{ matrix.os }}
#     strategy:
#         matrix:
#           os: [ubuntu-latest, macos-14, windows-latest]
#           python-version: [3.10, 3.11, 3.12]

#           # include:
#           #   - images: amd64/ubuntu-latest
#           #     os: ubuntu-latest
#     steps:
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: ${{ matrix.python-version }}

# Correct Answer       
        
# name: Installing Python