name: Installing Python

on: #[push]
workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
    runs-on: ubuntu-latest
    steps:
        os: [ ubuntu-latest, macos-14, windows-latest ]
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
        
